### ISSUE TITLE
Politeiagui redesign/refactoring coordination and checklist

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1205]
This issue describes the work in progress for the [redesign](https://github.com/decred/dcrdesign/issues/77) and refactoring implementation of politeiagui. It includes an overview of the design as well a check-list so anyone can track what has been accomplished so far. 
There are basically 6 milestones to be accomplished (listed at the end of this document), I expect 6 majors PRs for each of those and 'on-demand' PRs to deal with minor changes, fixes, and adjustments.
 
### Developers
The politeiagui devs are split into 2 teams. The team redesign is composed of @tiagoalvesdulce and me. It is possible and expected that a few overlaps will happen along the way.

### Pi-UI library
The [pi-ui](https://github.com/tiagoalvesdulce/pi-ui) library is being built to accommodate the new UI components and layouts.  The lib doc is automatically deployed [here](https://compassionate-lalande-d3ef5d.netlify.com)

### General Goals
- Implement the new design layout
- Remove the politeiagui dependency on the `snew-classic-ui
` library
- Allow features and context-specific elements to be customized from an external configuration source as described on #1067

### Technical Goals
- Make the codebase structure more context-driven in order to have high order components closer to the integration code
- Reduce the code dependency on Redux by using new React technologies such as hooks and context API

### Work in progress

- [x] **User**
    - [x] Login 
       - [x] Layout
       - [x] Integration
    - [x] Signup
      - [x] Layout
      - [x] Integration
      - [x] Custom config: toggle admin invite
   - [x] Reset password
      - [x] Request Layout
      - [x] Reset Layout 
      - [x] Integration
  - [x] Verify account email 
      - [x] Request Layout
      - [x] Reset Layout 
      - [x] Integration
  - [x]  Privacy Policy
       - [x] Layout 
       - [x] Custom config: change content based on preset type (cms, proposals)
  - [x] Detail
      - [x] Layout
      - [x] List information
      - [x] Manage Identity 
      - [x] Change username
      - [x] Change password 
      - [x] Preferences
  - [x] Paywall
      - [x] Layout
      - [x] Integration
      - [x] Custom config: enable/disable
   - [x] e2e integrations
        - [x] Routes (public, authenticated and admin-authenticated)

- [x] **Proposal**
    -  [x] Public List
        - [x] Layout
        - [x] Integration
        - [x] Search proposal capability
    - [x] Admin List
        - [x] Layout 
        - [x] Integration
    - [x] New
        - [x] Layout
        - [x]  Markdown Editor
        - [x] Files uploader and display of files
        - [x] Integration
    - [x] Edit
        - [x] Layout
        - [x] Integration
    - [x] Detail
        - [x] Layout
        - [x] Integration
        - [x] Version picker / version diff 
   - [x] User proposals list (account detail)
   - [x] User proposals list (submitted/draft)

- [x] **Comment**
   - [x] Layout
   - [x] Integration
   - [x] Sorting
   - [x] Custom config: enable/disable comments, enable/disable voting on comments
   - [x] Censor comments
   - [x] Highlight new comments since last visit

- [x] **Integrate comments**
   - [x] Proposals
        

**[DONE] Miestone 1 - User authentication:** Login, Signup, Reset Passwrod, Verify account email, Privacy Policy, e2e integrations
**[DONE] Milestone 2 - User account management :** User detail, Paywall [
**[DONE] Milestone 3 - Proposal:** Public list, admin list, new, edit, detail 
**[DONE] Milestone 4 - Comment:** All comment items
**[DONE]Milestone 5 - Integrate proposal comments**

**Comment by fernandoabolafio** [comment]
## Status Update:

As of now, we are close to having the major functionalities for the pi redesign implemented. The most updated version can be accessed [here](https://pi-redesign.authit.co/). At this point, we are no longer divided into 2 different teams as the other developers @thi4go @camus-code and @victorgcramos have joined us to drive the redesign to the competition. We currently have 3 PRs for the redesign being reviewed. The major functionalities we're currently working on are:
- FInish Proposal Credits and account management (@tiagoalvesdulce @fernandoabolafio)
- Proposal files attachment and display (@thi4go)
- User session expiration (@victorgcramos)
- Components and issues fix for pi-ui (@camus-code)
- Admin page and proposal actions (@fernandoabolafio)

Once we're done with the WIPs described above we will be in a good stage for having the first deployment to testnet and experiment the new frontend. A few other minor functionalities should be added shortly thereafter.

**Comment by fernandoabolafio** [comment]
Done
