### ISSUE TITLE
[redesign] Production release checklist 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1497]
This issue list the items we need to test and verify before going to production. We need to go through this list and make sure we validate that every item is working as expected. This test list is specially intended for devs but any other person from the community is welcome to test as well.

**Please, make sure to test the layout is working properly for mobile and desktop views and write down with your report anything that doesn't look good to you. A good idea is to test the following features by frequently switching the layout from mobile to desktop and vice versa.**

Normal User
- [ ] Create a Pi account
  - [ ] Verify email
  - [ ] Pay user registration fee
- [ ] Reset password
- [ ] Change password
- [ ] Update identity
- [ ] Purchase proposal credits
- [ ] Submit a proposal
- [ ] Edit proposal
  - [ ] Edit unvetted proposal
  - [ ] Edit vetted proposal
- [ ] Comment
  - [ ] Comment on proposal
  - [ ] Comment on comment
  - [ ] Vote on comment
  - [ ] Sort comments
- [ ] Authorize proposal vote
- [ ] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or it's identity is invalid:
   - [ ] Create a proposal
   - [ ] Comment
   - [ ] Vote on a comment
   - [ ] Authorize proposal vote

Admin User
- [ ] Mark user registration fee as paid
- [ ] Rescan paywall address
- [ ] Make proposal public
- [ ] Deactivate and Activate user account
- [ ] Expire user email verification token
- [ ] Expire user reset password verification token
- [ ] Expire user update identity verification token
- [ ] Censor proposal
- [ ] Abandon proposal
- [ ] Start proposal vote
- [ ] Censor comment
- [ ] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or its identity is invalid:
   - [ ] Censor comment
   - [ ] Approve/Abandon/Censor Proposal
   - [ ] Start proposal vote

**Comment by victorgcramos** [comment]
I found something regarding the mobile view for replies. Some buttons are not being shown due to a large number of replies. Sometimes, the user is unable to click on 👍, as you can see below:
![Screen Shot 2019-10-16 at 13 07 36](https://user-images.githubusercontent.com/22639213/66938657-fd886800-f017-11e9-9b37-91a5a1a1053b.png).

**Comment by fernandoabolafio** [comment]
My checklist:

Normal User
- [ ] Create a Pi account
  - [ ] Verify email
  - [ ] Pay user registration fee
- [ ] Reset password
- [ ] Change password
- [ ] Update identity
- [ ] Purchase proposal credits
- [ ] Submit a proposal
- [ ] Edit proposal
  - [ ] Edit unvetted proposal
  - [ ] Edit vetted proposal
- [ ] Comment
  - [ ] Comment on proposal
  - [ ] Comment on comment
  - [ ] Vote on comment
  - [ ] Sort comments
- [ ] Authorize proposal vote
- [ ] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or it's identity is invalid:
   - [ ] Create a proposal
   - [ ] Comment
   - [ ] Vote on a comment
   - [ ] Authorize proposal vote

Admin User
- [ ] Mark user registration fee as paid
- [ ] Rescan paywall address
- [ ] Make proposal public
- [ ] Deactivate and Activate user account
- [ ] Expire user email verification token
- [ ] Expire user reset password verification token
- [ ] Expire user update identity verification token
- [ ] Censor proposal
- [ ] Abandon proposal
- [ ] Start proposal vote
- [ ] Censor comment
- [ ] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or its identity is invalid:
   - [ ] Censor comment
   - [ ] Approve/Abandon/Censor Proposal
   - [ ] Start proposal vote

Others
- [ ] Verify that the mainnet data is showing correctly on https://pi-redesign.authit.co

**Comment by thi4go** [comment]
Starting tests to `test-proposals`

Normal User
- [x] Create a Pi account
  - [x] Verify email
  - [x] Pay user registration fee
- [ ] Reset password
- [ ] Change password
- [ ] Update identity
- [ ] Purchase proposal credits
- [ ] Submit a proposal
- [ ] Edit proposal
  - [ ] Edit unvetted proposal
  - [ ] Edit vetted proposal
- [ ] Comment
  - [ ] Comment on proposal
  - [ ] Comment on comment
  - [ ] Vote on comment
  - [ ] Sort comments
- [ ] Authorize proposal vote
- [ ] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or it's identity is invalid:
   - [ ] Create a proposal
   - [ ] Comment
   - [ ] Vote on a comment
   - [ ] Authorize proposal vote

Admin User
- [ ] Mark user registration fee as paid
- [ ] Rescan paywall address
- [ ] Make proposal public
- [ ] Deactivate and Activate user account
- [ ] Expire user email verification token
- [ ] Expire user reset password verification token
- [ ] Expire user update identity verification token
- [ ] Censor proposal
- [ ] Abandon proposal
- [ ] Start proposal vote
- [ ] Censor comment
- [ ] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or its identity is invalid:
   - [ ] Censor comment
   - [ ] Approve/Abandon/Censor Proposal
   - [ ] Start proposal vote

Others
- [ ] Verify that the mainnet data is showing correctly on https://pi-redesign.authit.co

**Comment by victorgcramos** [comment]
Feedbacks:

1. **User payment address** `copy address` tooltip is overflowing the mobile width:
   ![Screen Shot 2019-10-23 at 12 23 54](https://user-images.githubusercontent.com/22639213/67409105-7e9fac00-f590-11e9-8d25-d0c61b82eac9.png)

2. **Purchase credits** form is displaying a fix `1`, and cannot be erased
    ![Screen Shot 2019-10-23 at 13 17 23](https://user-images.githubusercontent.com/22639213/67413678-f9b89080-f597-11e9-98d9-a349335a2f80.png)

3. **Version modal** information is overflowing the mobile width:
    ![Screen Shot 2019-10-23 at 14 20 30](https://user-images.githubusercontent.com/22639213/67418420-1e653600-f5a1-11e9-8382-1966e9a527d0.png)


Normal User
- [x] Create a Pi account
    - [x] Verify email
    - [x] Pay user registration fee
- [x] Reset password
- [x] Change password
- [x] Update identity
- [x] Purchase proposal credits
- [x] Submit a proposal
- [x] Edit proposal
    - [x] Edit unvetted proposal
    - [x] Edit vetted proposal
- [x] Comment
    - [x] Comment on proposal
    - [x] Comment on comment
    - [x] Vote on comment
    - [x] Sort comments
- [x] Authorize proposal vote
- [x] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or it's identity is invalid:
    - [x] Create a proposal
    - [x] Comment
    - [x] Vote on a comment
    - [x] Authorize proposal vote

Admin User

- [x] Mark user registration fee as paid
- [x] Rescan paywall address
- [x] Make proposal public
- [x] Deactivate and Activate user account
- [x] Expire user email verification token
- [x] Expire user reset password verification token
- [x] Expire user update identity verification token
- [x] Censor proposal
- [x] Abandon proposal
- [x] Start proposal vote
- [x] Censor comment
- [x] Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or its identity is invalid:
    - [x] Censor comment
    - [x] Approve/Abandon/Censor Proposal
    - [x] Start proposal vote

**Comment by fernandoabolafio** [comment]
@victorgcramos can you create issues for the things you found?

**Comment by MariaPleshkova** [comment]
Feedback for Normal user (haven't checked admin views yet):

1. When you're not logged in and open the menu you can see an empty extra section below
![image](https://user-images.githubusercontent.com/8841018/67568256-5650b280-f734-11e9-9586-73a1d499fa37.png)

2. **Spec**: 
![image](https://user-images.githubusercontent.com/8841018/67567054-df1a1f00-f731-11e9-83b8-e32f76f4cc1f.png)

**Implementation**: 
![image](https://user-images.githubusercontent.com/8841018/67567067-ea6d4a80-f731-11e9-9add-c9ace2a34e93.png)

3. It should be right-aligned
![image](https://user-images.githubusercontent.com/8841018/67567699-0ae9d480-f733-11e9-86df-b52f75c12c13.png)

4. Need more space between the title and cross icon and under the last button

**Spec**: 
![image](https://user-images.githubusercontent.com/8841018/67567867-69af4e00-f733-11e9-886f-79691d6690d2.png)

**Impl**: 
![image](https://user-images.githubusercontent.com/8841018/67567849-5d2af580-f733-11e9-9026-fc5eb1eb6fa6.png)
![image](https://user-images.githubusercontent.com/8841018/67567935-95323880-f733-11e9-8888-bbbe0b95d48d.png)

5. I'd rather leave more space of blue rectangle for where red arrows are (the same as showed with green arrows)
![image](https://user-images.githubusercontent.com/8841018/67569075-89944100-f736-11e9-81b4-d782f7165eee.png)

6. I think we should add a success message when password is changed

7. Yeah, as @victorgcramos said, we cannot remove the first digit from here, only add more and use arrows up/down to change the first one
![image](https://user-images.githubusercontent.com/8841018/67569811-87cb7d00-f738-11e9-9435-fdf4492e0b5e.png)

8. I think we have to show less symbols of tx number to leave more space between the title and the number itself
![image](https://user-images.githubusercontent.com/8841018/67570006-04f6f200-f739-11e9-9490-40784e0deda6.png)

Smth like this: 
![image](https://user-images.githubusercontent.com/8841018/67570025-104a1d80-f739-11e9-969c-107d7d7166b4.png)

9. Don't you think than when we click on this Plus button, the system should open a pop up with "Purchase Proposal Credits" straight away? Without goint to Credits tab. It seems like an extra action.
Btw this plus sign has to be center aligned unside its blue square.
![image](https://user-images.githubusercontent.com/8841018/67570237-877fb180-f739-11e9-822f-4c87a994d5ef.png)

10. I think this cross is too small 
![image](https://user-images.githubusercontent.com/8841018/67570448-18ef2380-f73a-11e9-9b53-1a2ae34955ae.png)

11. Proposal on mobile 
![image](https://user-images.githubusercontent.com/8841018/67571102-c9115c00-f73b-11e9-9033-c309511851cc.png)

12. When I unvoted, I still see the color of voted hand
![image](https://user-images.githubusercontent.com/8841018/67571173-f100bf80-f73b-11e9-975b-2b4518fdf711.png)

13. I think when we clicked on Reply and one more input field appears, we have to add Cancel button near Add coment one. Bc it's not obvious that we can close this field by clicking on Reply again
![image](https://user-images.githubusercontent.com/8841018/67571252-332a0100-f73c-11e9-8555-56c02a09751e.png)

15. When I click on version 'n' (to see versions changes), then choose "Attachments changes", then close it and choose another version, the pop up opens on Attachment changes again instead of Text changes

16. I think we have to make the distance between these 2 links more, as they look like one long link right now
![image](https://user-images.githubusercontent.com/8841018/67571767-6de06900-f73d-11e9-87c3-8ce6a9b12504.png)

17. Maybe it would be better to remove New proposal button from the header when we open another user's profile? What do you think? I just thought it looks a little bit confusing when I see this button next to someone's name, like I'm able to create a proposal for him, idk...
![image](https://user-images.githubusercontent.com/8841018/67572005-f65f0980-f73d-11e9-8e8c-a257e613db91.png)

**Comment by tiagoalvesdulce** [comment]
Modal content not respecting the padding when the proposal title is long

<img width="604" alt="Screen Shot 2019-10-25 at 10 10 50" src="https://user-images.githubusercontent.com/13955303/67574076-28597700-f710-11e9-891f-e1be7b81a48f.png">

**Comment by fernandoabolafio** [comment]
Thanks for the thoughtful review @MariaPleshkova. About your comments:
1. Currently being addressed on #1513
5. That's the normal behavior when the content starts on a line and ends in the next one. Otherwise, it would look like two different things. 
7. Agreed (Issue created already https://github.com/decred/politeiagui/issues/1386)
9. That was how it worked on the old site and you decide to not use a modal for that so I think we should keep as it is for now. It's not a highly used function anyway.
10. Needs fixing
11. What's wrong with the proposal? You can scroll horizontally to see the remaining content.
12. That's because you are still hovering the icon. Should it be different? Like, use a different color for hovering and indicating the selected option.

The comment numbers I didn't mention I will create issues for us to working on them.

**Comment by victorgcramos** [comment]
Hey @fernandoabolafio, can #1524 be a fix for #1386?

**Comment by tiagoalvesdulce** [comment]
@victorgcramos It doesn't close the issue because it doens't match the specs but your PR is a good improvement so #1386 won't hold the release.

**Comment by MariaPleshkova** [comment]
@fernandoabolafio 
2. But the thing is that on smaller screens the line "Don't have an account? ..." should move under "Privacy policy". This way it will look more common for mobile screens
4. What function do you mean? I don't understand what my comment you replied to under the 4

One more thing I've just noticed: I don't think text size should change when I select Preview while creating a proposal

**Comment by fernandoabolafio** [comment]
@MariaPleshkova the GitHub markdown messed up with my numbers. It was showing a different thing than the raw text. Anyway, it's updated now. Let me know if makes more sense to you now.

**Comment by MariaPleshkova** [comment]
Reviewed admin views. LGTM. But there's one thing that isn't clear, I'm not sure should it work like this or not. It's regarding the last point in the check list "Make sure the following actions are correctly blocked (or errors are correctly shown) when the user has not yet paid the paywall or its identity is invalid:
 -Censor comment
 -Approve/Abandon/Censor Proposal
 -Start proposal vote "
I created 2 accounts, one is an admin and another-normal user. Created an issue from normal user account and then made its identity invalid. So as far as I understood I shouldn't be able to start voting for this prop from admin account as its creator has an anvalid key. But I still could start voting. I don't know if I'm right or not, just in case if it is what you meant in your list.

And another thing with modal on smaller screens:
![image](https://user-images.githubusercontent.com/8841018/67665404-b2a51380-f97a-11e9-8820-a1786caa21d8.png)
I'd better start input fields from where above icon starts. And also would center-align the button and "Or paste in your own" text.

**Comment by MariaPleshkova** [comment]
@fernandoabolafio 

5. Ok, it makes sense I guess
9. But the modal opens if we click on Purchase more here
![image](https://user-images.githubusercontent.com/8841018/67667557-23e6c580-f97f-11e9-90a1-87fe98ed7410.png)
![image](https://user-images.githubusercontent.com/8841018/67667836-cacb6180-f97f-11e9-831a-f9cf3fe99e9a.png)

What I suggest is to open the same modal after clicking on Plus icon near username straight away and not to go to Credits tab first

11. ok
12. Oh, it happened because I checked it on dev mode. It works cool without it, yes. Sorry

**Comment by fernandoabolafio** [comment]
@MariaPleshkova mostly of your suggestions are addressed here https://github.com/decred/politeiagui/pull/1527

Regarding other comments:

> I created 2 accounts, one is an admin and another-normal user. Created an issue from normal user account and then made its identity invalid. So as far as I understood I shouldn't be able to start voting for this prop from admin account as its creator has an invalid key. But I still could start voting. I don't know if I'm right or not, just in case if it is what you meant in your list.

This is the expected behavior. The actions are blocked for the user who has an invalid identity. In your test scenario when the non-admin user created the proposal his identity was valid. In the admin user side, his identity is also valid at the moment he is starting the vote so all good. The vote shoudn't be started if **the admin key was invalid**. 

> What I suggest is to open the same modal after clicking on Plus icon near username straight away and not to go to Credits tab first

I rather keep it as it is right now because behind the scenes we start polling the API for credits update then the user accesses the "credits" tab so all the hooks are in there and this is already more complex than I'd like. We have plans for adding WebSockets for proposal credits purchase in the future, which will give us more flexibility. Furthermore, this isn't a very often visited feature so I think it's ok for the user to be 2 clicks away instead of 1.

**Comment by MariaPleshkova** [comment]
Ok @fernandoabolafio . I got you. Thanks for the reply
