### ISSUE TITLE
[cms-v2] Coordination and Checklist

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1685]
This issue is meant to centralize the general information about the development of the new version of the CMS GUI client. 
The work will be done in a different branch than master, the [cmsv2](https://github.com/decred/politeiagui/tree/cmsv2) until the work is advanced enough. This branch has to be up to date with master on every PR before the merge. 

Here is the checklist:

- [x] Authentication 
     - [x] Login
     - [x] Signup
     - [x] Reset password
     - [x] Resend verification email
- [x] Invoice
    - [x] User List
    - [x] Admin List
    - [x] New
    - [x] Admin actions (approve, reject, dispute)
    - [x] Comments
    - [x] Draft
    - [x] Edit
- [x] User/Contractor 
    - [x] Invite
    - [x] Manage (type, domain, supervisors)
- [x] Payouts
    - [x] Generate 
    - [x] Summary List
- [x] DCC
    - [x] New
    - [x] Details
    - [x] List 
    - [x] Draft
    - [x] Comments
    - [x] Admin actions (approve/reject) 
    - [x] Actions (Support/oppose)
 
### Methodology

In order to accomplish the work described above and keep the current website working, this work will be completed in a separated branch which will be constantly synchronized with the master branch. Once this refactoring is done, there should not be any backwards compatibility with the old side. Meaning that all remaining artifacts and libraries ("snew-classic-ui" for instance) will be removed.

**Comment by tiagoalvesdulce** [comment]
Completed!
