### ISSUE TITLE
RFP Coordination Checklist

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1951]
This issue is a guide for RFP Testing. Just an idea of what should we pay attention to:

Reference: 
*multi: Add RFP proposal. https://github.com/decred/politeia/pull/1054*

User:

- [ ] Create an RFP **Proposal**
- [ ] Edit an RFP **Proposal**
- [ ] Authorize RFP Proposal voting
- [ ] Wait for RFP Proposal to reach the min quorum
- [ ] Create multiple RFP **Submissions**
- [ ] Edit an RFP **Submission**
- [ ] Wait for RFP Proposal Deadline gets ended
- [ ] Comments on an RFP Proposal
  - [ ] New comment
  - [ ] Upvote and Downvote comments
  - [ ] Reply comments

Admin:
- [ ] Create an RFP Proposal
- [ ] Make it public & start voting on RFP
- [ ] Approve it by casting enough votes
- [ ] When RFP Proposal is approved, add RFP Submissions
   - [ ] Create multiple public submissions
- [ ] Vote on multiple RFP Submissions
- [ ] Censorship:
  - [ ] Censor RFP Comments
  - [ ] Mark RFP Proposal as Spam
  - [ ] Mark RFP Submission as Spam

Things to keep in mind:
  - Once the approved RFP submission deadline expires, an admin can start the voting process on the RFP submissions at any time. This is a new type of vote called a runoff vote. Whe an admin starts the runoff vote, the voting period on all public, non-abandoned RFP submissions will
begin simultaneously
  - Unlike a normal proposal vote, no vote authorization is required from the submission author
  - The winning proposal is the proposal that meets the quorum % requirement, meets the pass % requirement, and that has the most net yes votes. *Note: this means that it will be possible for a proposal to meet the quorum and pass requirements but still be rejected if it does
not have the most net yes votes.*
  - A link is not official until the RFP submission is made public, leaving this decision in the hands of the admins.

@tiagoalvesdulce @amassarwi @thi4go @lukebp feel free to add suggestions for this issue and checklist! Thanks!

**Comment by amassarwi** [comment]
Proposal form need some love on mobile:
![image](https://user-images.githubusercontent.com/10324528/83189306-546b2980-a131-11ea-88bd-1523c07a243a.png)

PS: on it

**Comment by victorgcramos** [comment]
Got this error when selecting the first available date on RFP Proposal deadline:
`74 invalid proposal linkby: linkby period cannot be shorter than 1209600 seconds`
<img width="1233" alt="Captura de Tela 2020-05-28 às 16 54 44" src="https://user-images.githubusercontent.com/22639213/83193637-c6ca1280-a10d-11ea-8725-968ceef81539.png">

**Comment by victorgcramos** [comment]
This `RFP` badge Font looks awkward
<img width="819" alt="Captura de Tela 2020-05-28 às 18 06 03" src="https://user-images.githubusercontent.com/22639213/83193750-ecefb280-a10d-11ea-9067-317152cc0861.png">

**Comment by amassarwi** [comment]
@victorgcramos regarding the icon font, I've discussed it with @tiagoalvesdulce and ideally we should get a different .svg, the problem is that we use plain text inside the .svg which uses the default browser font-family, I will try fix it with css, but ideally this should be part of the .svg I mean the letters should be also vectors and not plain text, this will also fix the scaling problems we have, on some screens the tag looks a bit like a rectangle.

**Comment by tiagoalvesdulce** [comment]
@MariaPleshkova @linnutee is there a better svg for that?

**Comment by victorgcramos** [comment]
Sure! Let's create an issue for this specifically

**Comment by amassarwi** [comment]
Sure, on it.

**Comment by MariaPleshkova** [comment]
@tiagoalvesdulce added to #1952

**Comment by amassarwi** [comment]
Done:
> Proposal form need some love on mobile 
#1956 

> This RFP badge Font looks awkward
#1957

WIP:

> `74 invalid proposal linkby: linkby period cannot be shorter than 1209600 seconds`
#1963

**Comment by victorgcramos** [comment]
#1963 is closed.

**Comment by amassarwi** [comment]
![all clear](https://media.giphy.com/media/fSSbirL3Ew0zC/giphy.gif)

**Comment by tiagoalvesdulce** [comment]
RFP is live!
