### ISSUE TITLE
[pi] E2E Tests Coordination checklist

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2229]
Since e2e tests are now available, I decided to group all features that must be tested on Pi.

## Tests for Pi

- [ ]  Public Proposal List
- [ ]  Comments:
    - [x]  Comment on a proposal
    - [x]  Like comment
    - [ ]  Flat mode
    - [ ]  Single comment thread
    - [x]  Reply

- [ ]  Proposal:
    - [x]  New proposal
    - [x]  Edit proposal
    - [ ]  Details
    - [ ]  RFP Proposal
    - [ ]  RFP Submission

- [ ]  User:
    - [ ]  Identity
    - [ ]  Account
    - [ ]  Preferences
    - [ ]  Credits
    - [ ]  Proposals
        - [ ]  Submitted
        - [ ]  Drafts
    - [ ]  Change Username

- [x]  Login
- [x]  Registration

- [ ]  Admin:
    - [ ]  Accounts:
        - [x]  View some user account
        - [ ]  Deactivate and reactivate some user account
        - [x]  Search users
        - [ ]  Mark registration fee as paid for some user
        - [ ]  Rescan Credits
    - [x]  Comments:
        - [x] Censor Comment
    - [x]  Proposal:
        - [x] Report as spam
        - [x] Approve
        - [x] Abandon
        - [x] Authorize Vote

@amassarwi @thi4go @tiagoalvesdulce feel free to give your thoughts!

**Comment by tiagoalvesdulce** [comment]
I'm adding this to v1.1.0 to enforce we should also fix the broken e2e tests.

**Comment by lukebp** [comment]
Closing due to inactivity.  I believe we also have more up-to-date issues for e2e tests.
