### ISSUE TITLE
v1.3.0 release testing

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2653]
This issue serves to document testing the v1.3.0 release on test-proposals.

The release contents can be seen in #2652. Please verify all user facing features or bug fixes that you wrote are working correctly on test-proposals. Post a comment to this issue to document the verification.

**Comment by lukebp** [comment]
Amass is out for a few days so I tested his features for him.  The following have been tested and verified:

feat: Improve identity error message. [amass01] ([#2623](https://github.com/decred/politeiagui/pull/2623))  
feat: multiple billing status changes. [amass01] ([#2629](https://github.com/decred/politeiagui/pull/2629))  
feat: Display proposal status reason. [amass01] ([#2625](https://github.com/decred/politeiagui/pull/2625))  
feat: Add set billing status & proposal statuses. [amass01] ([#2609](https://github.com/decred/politeiagui/pull/2609))  

I found the following bugs:

- List view re-ordering bug. ([#2654](https://github.com/decred/politeiagui/issues/2654))
- Incorrect 'Go Back' button behavior. ([#2655](https://github.com/decred/politeiagui/issues/2655))

**Comment by victorgcramos** [comment]
- [x] test: Add e2e tests for 2FA workflow [victorgcramos] ([#2601](https://github.com/decred/politeiagui/pull/2601))
- [x] seo: Add SEO meta tags for CMS and Pi. [victorgcramos] ([#2614](https://github.com/decred/politeiagui/pull/2614)) 
- [x] fix: Comments navigation issues [victorgcramos] ([#2638](https://github.com/decred/politeiagui/pull/2638)) 
- [x] test: E2E Mock API structure [victorgcramos] ([#2624](https://github.com/decred/politeiagui/pull/2624)) 

Found one bug and pushed the following PR fixing it:
- https://github.com/decred/politeiagui/pull/2661

**Comment by vibros68** [comment]
## Verified on test-proposals: ##

* [refactor: Clear 2FA code on error. #2621](https://github.com/decred/politeiagui/pull/2621)
* [feat(theme toggle switch): Update theme toggle switch styles.  #2588](https://github.com/decred/politeiagui/pull/2588)
* [refactor: Replace hard coded page sizes. #2622](https://github.com/decred/politeiagui/pull/2622)
* [fix: Proposal diff bugs.  #2639](https://github.com/decred/politeiagui/pull/2639)
* [ux: Add min loading time to list views.#2628](https://github.com/decred/politeiagui/pull/2628)
* [feat: change format date view to a more readable format #2640](https://github.com/decred/politeiagui/pull/2640)

## Found one bug ##
* Go to the [main page](https://test-proposals.decred.org/). Click on `Abandoned` tab. Click on any proposal on the tab. On the detail page, click on `Go Back` button. The web site redirect to [Under Review](https://test-proposals.decred.org) tab instead of [Abandoned](https://test-proposals.decred.org/?tab=abandoned) tab

**Comment by victorgcramos** [comment]
Found one bug:
- #2664

**Comment by lukebp** [comment]
v1.3.0 has been deployed to production.
