### ISSUE TITLE
QA checklist for major pull requests 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#977]
We need a QA checklist in order to test major updates as per [this discussion](https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$154704212011964QEPSx:decred.org?via=decred.org&via=matrix.org&via=zettaport.com).
This checklist has to cover most of the critical user flows such as sign up, log in, creating a proposal, editing a proposal, etc. 
This QA checklist may be dropped once we have automated e2e tests.

**Comment by lukebp** [comment]
Here's a first pass.

Normal User
- [ ] Create a Pi account
  - [ ] Verify email
  - [ ] Pay user registration fee
- [ ] Reset password
- [ ] Change password
- [ ] Update identity
- [ ] Purchase proposal credits
- [ ] Submit a proposal
- [ ] Edit proposal
  - [ ] Edit unvetted proposal
  - [ ] Edit vetted proposal
- [ ] Comment
  - [ ] Comment on proposal
  - [ ] Comment on comment
- [ ] Authorize proposal vote
- [ ] Vote on proposal
- [ ] Deactivate account

Admin User
- [ ] Mark user registration fee as paid
- [ ] Rescan paywall address
- [ ] Make proposal public
- [ ] Censor proposal
- [ ] Abandon proposal
- [ ] Start proposal vote
- [ ] Censor comment

**Comment by lukebp** [comment]
Closing due to inactivity.
